server:
  port: 8005
spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.3.75.204:3306/st?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: Aa112211
  redis:
    host: 119.3.75.204
    port: 6379
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*Mapper.xml
machine-id: 2
data-center-id: 2
