server:
  port: 8888

# 如果路由方式是serviceId的方式，那么ribbon的生效，如果是url的方式，则zuul.host开头的生效
ribbon:
  ReadTimeout: 15000
  ConnectTimeout: 10000

spring:
  application:
    name: gateway
  redis:
    host: 119.3.75.204
    port: 6379
  cloud:
    nacos:
      server-addr: 119.3.75.204:8848
      username: nacos
      password: nacos
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: public-auth
          # lb代表从注册中心获取服务，且已负载均衡方式转发
          uri: lb://oauth2
          predicates:
            - Path=/public-auth/**
          # 加上StripPrefix=1，否则转发到后端服务时会带上consumer前缀
          filters:
            - StripPrefix=1
        - id: user-order
          # lb代表从注册中心获取服务，且已负载均衡方式转发
          uri: lb://order
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix=2
#        - id: admin-user
#          # lb代表从注册中心获取服务，且已负载均衡方式转发
#          uri: lb://learn-shop-admin-user
#          predicates:
#            - Path=/admin-user/**
#        - id: core-order
#          # lb代表从注册中心获取服务，且已负载均衡方式转发
#          uri: lb://learn-shop-core-order
#          predicates:
#            - Path=/core-order/**
#        - id: core-product
#          # lb代表从注册中心获取服务，且已负载均衡方式转发
#          uri: lb://learn-shop-core-product
#          predicates:
#            - Path=/core-product/**
#        - id: core-search
#          # lb代表从注册中心获取服务，且已负载均衡方式转发
#          uri: lb://learn-shop-core-search
#          predicates:
#            - Path=/core-search/**
#        - id: core-seckill
#          # lb代表从注册中心获取服务，且已负载均衡方式转发
#          uri: lb://learn-shop-core-seckill
#          predicates:
#            - Path=/core-seckill/**
#        - id: public-job
#          # lb代表从注册中心获取服务，且已负载均衡方式转发
#          uri: lb://learn-shop-public-job
#          predicates:
#            - Path=/public-job/**
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8001/rsa/publicKey' # 获取公钥

# 自己定义安全配置
secure:
  client: # 登陆客户端配置
    client-id: webapp
    client-secret: webapp
    scope: webapp
    grant-type: password
    access-token-uri: "www.baidu.com"
  white-list:
    - "/actuator/**"              # 健康检查
    - "/userApi/*"                # 获取用户信息
    - "/public-auth/oauth/token"  # 获取token或者刷新token
    - "/public-auth/rsa/publicKey"  # 获取公钥
    - /dataRecovery/initData     # 数据还原
    # swagger 配置
    - /v3/**
    - /**/v3/**
    - /swagger-resources/**
    - /swagger-resources
    - /course/coursebase/**
    - /swagger-ui/**
    - /favicon.ico
    - /**/*App/**
  need-check:
    - "/**/*Api/**"
    - "/*Api/**"
    - "/api/**"